### ISSUE TITLE
NBP Bearing Blocks 100012 and 100001 contain conflicting dimensions

### ISSUE THREAD

**Issue by billstrong** [openrelics/enigma#10]
The topmost dimensioned point in the Nachbauproject drawing is the center of large arc R27.1, with height above bottom surface 115.7mm flat. Sketch constraints as of 100001 v21 and 100012 v14 prevent this dimension from matching the NBP reference; the actual dimension is 115.703mm.

**Comment by mariusstrom** [comment]
@billstrong I'm tempted to label this won't fix and closed given the 3 micron difference. It could certainly be attributable to a measurement tolerance issue.

**Comment by billstrong** [comment]
I'm fine with it!
