### ISSUE TITLE
NBP 1000027 unable to constrain to NBP drawings

### ISSUE THREAD

**Issue by mariusstrom** [openrelics/enigma#20]
NBP specifies a interior R0.5 bend, but the model per the constraints defined gets driven to R0.3 bend:

![image](https://user-images.githubusercontent.com/22438813/95156465-82015880-074b-11eb-84a2-4212ba50b005.png)

![image](https://user-images.githubusercontent.com/22438813/95156496-90e80b00-074b-11eb-902c-37454ca4d84a.png)

**Comment by billstrong** [comment]
The bend was constrained to be concentric to the outside curve. I deleted this constraint and replaced the driven (R0.30) with a true dimension.
