### ISSUE TITLE
Fusion doesn't allow a coil feature to act as a joint origin

### ISSUE THREAD

**Issue by billstrong** [openrelics/enigma#22]
We cannot constrain simple springs in assemblies because of this issue. A workaround will be necessary.

**Comment by billstrong** [comment]
Determined that it is possible to use the origin of the component as a joint origin.

**Comment by mariusstrom** [comment]
I wonder if arbitrary points can be defined in the component to use as the joint. If so, we might consider putting "utility" points along key spring points (ends, bends, etc.) to use as joints.

**Comment by billstrong** [comment]
They can. I started doing this but haven't needed anything like that yet.
